language: node_js
node_js:
  - "node"
  - "13"
  - "12"
  - "10"
  

install: yarn install --frozen-lockfile

script:
  - yarn test-format # is formatting OK
  - yarn test-cli    # is provided build OK
  - yarn test        # is provided source OK


before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
